# Generated by Django 4.0.2 on 2024-03-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='membership_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='membership_start_date',
            field=models.DateField(null=True),
        ),
    ]
