# Generated by Django 4.0.2 on 2024-03-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0002_alter_userprofile_membership_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='membership_end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='membership_start_date',
            field=models.DateField(blank=True),
        ),
    ]
